// Dataverse schema definition for the Lending Due Diligence (LDD) code app.
// Mirrors the Pega CIBC Lending Due Diligence data model (Business Control / RM Escalation flow).
export const PREFIX = 'ava';
export const SOLUTION = 'LendingDueDiligence';

const S = (name, len = 200) => ({ kind: 'string', name, len });
const M = (name) => ({ kind: 'memo', name });
const I = (name) => ({ kind: 'int', name });
const D = (name) => ({ kind: 'decimal', name });
const MON = (name) => ({ kind: 'money', name });
const DT = (name) => ({ kind: 'datetime', name });
const DO = (name) => ({ kind: 'dateonly', name });
const B = (name) => ({ kind: 'bool', name });
const L = (name, target) => ({ kind: 'lookup', name, target });

export const tables = [
  {
    schema: 'ava_LddRefData',
    display: 'LDD Reference Data',
    plural: 'LDD Reference Data',
    description: 'Application reference data (queue types, channels, product types, purposes, dispositions).',
    primary: { schema: 'ava_Name', display: 'Name', len: 400 },
    columns: [
      S('ava_RefType', 100),
      S('ava_RefCode', 100),
      S('ava_RefValue', 400),
      S('ava_NameFr', 400),
      I('ava_SortOrder'),
    ],
  },
  {
    schema: 'ava_LddEmployee',
    display: 'LDD Employee',
    plural: 'LDD Employees',
    description: 'Employee / operator reference data.',
    primary: { schema: 'ava_Name', display: 'Employee Name', len: 200 },
    columns: [
      S('ava_OperatorId', 50),
      S('ava_CoinsId', 50),
      S('ava_EmailAddress', 200),
      S('ava_JobTitle', 100),
      S('ava_Transit', 20),
      S('ava_Region', 100),
      S('ava_Market', 100),
      S('ava_City', 100),
      S('ava_Province', 50),
      S('ava_Channel', 100),
      S('ava_ManagerOperatorId', 50),
      S('ava_ManagerName', 200),
      S('ava_L2ManagerOperatorId', 50),
      S('ava_L2ManagerName', 200),
    ],
  },
  {
    schema: 'ava_LddReviewTemplate',
    display: 'LDD Review Template',
    plural: 'LDD Review Templates',
    description: 'Review type / review template configuration.',
    primary: { schema: 'ava_Name', display: 'Review Template Name', len: 200 },
    columns: [
      S('ava_ReviewTypeId', 50),
      S('ava_ReviewName', 200),
      S('ava_QueueType', 100),
      I('ava_RecommendSla'),
      DO('ava_ActivationDate'),
      DO('ava_DeactivationDate'),
    ],
  },
  {
    schema: 'ava_LddError',
    display: 'LDD Error',
    plural: 'LDD Errors',
    description: 'Primary / secondary error catalogue (English and French).',
    primary: { schema: 'ava_Name', display: 'Error (English)', len: 500 },
    columns: [
      S('ava_ErrorCode', 50),
      S('ava_NameFr', 500),
      S('ava_Category', 100),
    ],
  },
  {
    schema: 'ava_LddTransaction',
    display: 'LDD Transaction',
    plural: 'LDD Transactions',
    description: 'Lending transaction / application record sourced from the ingestion feed.',
    primary: { schema: 'ava_Name', display: 'Transaction Level Unique ID', len: 100 },
    columns: [
      S('ava_Source', 50),
      S('ava_ApplicationNumber', 50),
      DO('ava_ApplicationDate'),
      DO('ava_ApprovalDate'),
      DO('ava_FundedDate'),
      S('ava_PidDescription', 200),
      S('ava_CidDescription', 200),
      S('ava_Status', 50),
      S('ava_ApprovalType', 50),
      S('ava_Purpose', 200),
      S('ava_PropertyUsage', 100),
      S('ava_IncomeType', 100),
      S('ava_CustomerName', 200),
      S('ava_ProductType', 100),
      S('ava_Channel', 100),
      S('ava_Transit', 20),
      S('ava_MortgageNumber', 50),
      S('ava_MMortgageNumber', 50),
      S('ava_ClassNumber', 50),
      S('ava_OperatorId', 50),
      S('ava_OverriderId', 50),
      S('ava_Region', 100),
      S('ava_Market', 100),
      MON('ava_RequestedAmount'),
      MON('ava_FundedAmount'),
      I('ava_CreditScore'),
      D('ava_LoanToValue'),
      D('ava_Gdsr'),
      D('ava_Tdsr'),
    ],
  },
  {
    schema: 'ava_LddCase',
    display: 'LDD Business Control Case',
    plural: 'LDD Business Control Cases',
    description: 'Business Control case (RM escalation flow work object).',
    primary: { schema: 'ava_Name', display: 'Case ID', len: 50 },
    columns: [
      S('ava_Stage', 50),
      S('ava_Status', 60),
      S('ava_CaseOwner', 100),
      S('ava_QueueType', 100),
      S('ava_ReviewName', 200),
      S('ava_ReviewTemplateName', 200),
      S('ava_Channel', 100),
      S('ava_ProductType', 100),
      S('ava_Purpose', 200),
      S('ava_PidDescription', 200),
      S('ava_AssignedTo', 100),
      I('ava_SlaDays'),
      M('ava_TriageNotes'),
      S('ava_ReviewQuestion', 300),
      S('ava_ReviewAnswer', 300),
      S('ava_BcDueDiligence', 60),
      S('ava_EmployeeAccountable', 10),
      B('ava_AlignmentChange'),
      M('ava_AnalystComments'),
      I('ava_EscalationCount'),
      I('ava_CoachingCount'),
      I('ava_FyiCount'),
      S('ava_Mgr1OperatorId', 50),
      S('ava_Mgr1CoinsId', 50),
      S('ava_Mgr1Name', 200),
      S('ava_Mgr1Email', 200),
      S('ava_Mgr1JobTitle', 100),
      S('ava_Mgr1Transit', 20),
      S('ava_Mgr2OperatorId', 50),
      S('ava_Mgr2CoinsId', 50),
      S('ava_Mgr2Name', 200),
      S('ava_Mgr2Email', 200),
      S('ava_Mgr2JobTitle', 100),
      S('ava_Mgr2Transit', 20),
      S('ava_AttestationProvided', 10),
      M('ava_ResponseComments'),
      DT('ava_ResponseDate'),
      M('ava_FrontlineManagerComments'),
      S('ava_ReversalStatus', 60),
      S('ava_ReasonForReversal', 500),
      S('ava_CreatedByUser', 100),
      DT('ava_ResolvedOn'),
      S('ava_ResolvedBy', 100),
      L('ava_TransactionId', 'ava_lddtransaction'),
    ],
  },
  {
    schema: 'ava_LddRating',
    display: 'LDD Rating and Recommendation',
    plural: 'LDD Ratings and Recommendations',
    description: 'Per-role rating and recommendation captured during the Review stage.',
    primary: { schema: 'ava_Name', display: 'Role', len: 60 },
    columns: [
      S('ava_Role', 60),
      S('ava_OperatorId', 50),
      S('ava_EmployeeName', 200),
      S('ava_BcDueDiligence', 60),
      S('ava_EmployeeAccountable', 10),
      M('ava_Comments'),
      S('ava_AttestationProvided', 10),
      S('ava_ReversalStatus', 60),
      S('ava_ReasonForReversal', 500),
      M('ava_FrontlineManagerComments'),
      DT('ava_ResponseDate'),
      I('ava_SortOrder'),
      L('ava_CaseId', 'ava_lddcase'),
    ],
  },
  {
    schema: 'ava_LddCaseError',
    display: 'LDD Case Error',
    plural: 'LDD Case Errors',
    description: 'Errors selected against a rating and recommendation row.',
    primary: { schema: 'ava_Name', display: 'Error', len: 500 },
    columns: [
      S('ava_NameFr', 500),
      B('ava_IsPrimary'),
      L('ava_RatingId', 'ava_lddrating'),
      L('ava_ErrorId', 'ava_ldderror'),
    ],
  },
  {
    schema: 'ava_LddCaseTask',
    display: 'LDD Case Task',
    plural: 'LDD Case Tasks',
    description: 'Assignment / worklist entry for a Business Control case.',
    primary: { schema: 'ava_Name', display: 'Task Name', len: 200 },
    columns: [
      S('ava_TaskKey', 100),
      S('ava_Stage', 50),
      S('ava_AssignedTo', 100),
      S('ava_Status', 50),
      DT('ava_Goal'),
      DT('ava_Deadline'),
      DT('ava_AssignmentDate'),
      L('ava_CaseId', 'ava_lddcase'),
    ],
  },
];
